name: rfc1751
version: 0.1.1
synopsis: RFC-1751 library for Haskell
description: Convert 128-bit ByteString to/from 12 English words.
category: Data
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: PublicDomain
license-file: UNLICENSE
github: xenog/rfc1751.git
dependencies:
  - bytestring
  - cereal
  - vector
library:
  source-dirs:
    - src
  dependencies:
    - base ==4.*
tests:
  test-rfc1751:
    main: Spec.hs
    source-dirs:
      - tests
    ghc-options: -Wall
    dependencies:
      - base
      - hspec
      - rfc1751
      - QuickCheck
